### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by erikhuizinga** [navarog/wingsearch#3] opened 2020-09-20 20:29 UTC
Wingspan has been translated into many languages. Please add contents in other languages.

I can help providing text from the dutch base game, swift start pack and Europe expansion (all current 261 bird cards and bonus cards).

Suggestions:

- Select the default language based on browser preferences.
- Add a way to select a different language.
- Request for translations in various languages on the BoardGameGeek forums, as well as in the Wingspan Facebook group.

**Comment by navarog** [comment] 2020-09-21 17:50
@erikhuizinga, thanks for the suggestion! 

I have created the manual and template in [i18n folder](https://github.com/navarog/wingsearch/tree/master/i18n), so you can provide all the information for dutch, many thanks!

**Comment by erikhuizinga** [comment] 2020-09-23 11:14
Q: I see that I can provide an Excel spreadsheet to add support for a language. I wonder: what will you do with it to integrate it into your app? I guess that you'll process it into some serialised format, e.g. JSON? Therefore: could I, as a developer/experienced Git/GitHub user, provide you with a PR containing some file(s) that work properly under version control, instead of an Excel spreadsheet?

I understand the reason why use use an Excel spreadsheet source: it's a format most people know and can use. But I'd like to do this in steps, smaller commits, etc. So: why not support both methods? I could write directly in the target format, that you can plug directly into the application, maybe?

(And if that proves too much hassle, I can also still work in Excel, but it doesn't have my preference.)

**Comment by navarog** [comment] 2020-09-23 23:29
The reason for spreadsheet is exactly as you anticipated. To use a format most people know. It simplifies adding new data to minimum, which is definitely the case in the future when oceania expansion will be released. The goal is to have one simple pipeline which can process the data for all languages uniformly and one way to contribute for anyone. This reproducibility is the key, let's say after you, someone else will come who wants to fill in the oceania expansion for Dutch or fix some typo, it's much easier to find it in spreadsheet than json burried deep in the assets folder. Also it's much easier to fill a template in excel line than to fill empty fields in json.

Also, json would carry information about specifics of implementation, e.g. would it be array of three json objects for each sheet or one object with three attributes? Abstracting from that in pipeline which can transform all languages at once in the future when needed (no clue what oceania expansion will bring) is also one of my concerns. 

So if you want, you can write a json, I would probably transform the spreadsheet to something like this
```
{
birds: [...],
bonuses: [...],
other: {...}
}
``` 
where each bird and bonus row would be one object (similar to what I did with `wingspan-card-list.xlsx` and results in `master.json` in `scripts` folder) and other would be key-value pair. I would store it in `src/assets/data/i18n/nl.json`. If you choose to go with json, I would try to recreate the spreadsheet from it anyway because of the reasons mentioned above. I would really appreciate if you did it in the spreadsheet and optionally provide json.

**Comment by erikhuizinga** [comment] 2020-09-24 10:33
Thanks for your elaborate reply.

You're right. I hadn't thought about future contributors who may want to work with Excel instead of JSON. My request would mean that you'd need to have a reverse mapper from JSON to XLSX too.

Just one detail about your comment:

> Also, json would carry information about specifics of implementation [...]

The same is true for XLSX, because the sheets, rows, columns and cell contents are also structured according to a certain implementation. Furthermore, your XLSX to JSON mapper probably expects that specific XLSX structure, so that implementation detail leaks both ways: into the JSON and into the XLSX structure. No offense, just a statement.

I'll try to find some time to contribute and then I'll work in Excel.

**Comment by navarog** [comment] 2020-09-24 15:28
Looking forward to your contribution, feel free to do it in more parts, you can open PR with partially translated content and I can start implementing rest of the logic and we would be able to see partially translated cards in production.

**Comment by navarog** [comment] 2020-09-26 19:21
I've implemented my part, you can see it in #6 

It will stay open until @erikhuizinga provides the first chunk of data, then it goes to production and we should be able to switch to this translated chunk in the app.

**Comment by navarog** [comment] 2020-09-27 11:19
Few updates, I've received a dataset of bird names in 6 other languages, including dutch. I have published changes, so you should be able to see everything in production. This could speed things up for you. If possible, I'd really appreciate if you'd take a look at file `i18n/nl.xlsx` and review the names and add power descriptions whenever suits you.

**Closed** 2020-09-27 11:19 UTC

**Comment by erikhuizinga** [comment] 2020-09-28 14:13
That surely helps! I was already anxious about matching birds by scientific name.
